package com.adriano.journey.data.llm

import android.content.Context
import android.util.Log
import com.adriano.journey.domain.LargeLanguageModel
import com.google.mlkit.genai.prompt.Generation
import com.google.mlkit.genai.prompt.GenerativeModel
import com.google.mlkit.genai.prompt.TextPart
import com.google.mlkit.genai.prompt.generateContentRequest
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class LargeLanguageModelGeminiNano(
    private val context: Context,
    private val fallbackLlm: LargeLanguageModel,
    private val ioDispatcher: CoroutineDispatcher = Dispatchers.IO,
) : LargeLanguageModel {

    // Using ML Kit's GenerativeModel for Prompt API
    private val generativeModel: GenerativeModel = Generation.getClient()
    private val scope = CoroutineScope(ioDispatcher)
    private var isGeminiNanoAvailable = false
    private var isCheckingStatus = true

    init {
        checkGeminiNanoStatus()
    }

    private fun checkGeminiNanoStatus() {
        scope.launch {
            try {
                Log.d("GeminiNano", "Checking Gemini Nano status...")
                // Temporary simplified assumption
                isGeminiNanoAvailable = true
            } catch (e: Exception) {
                Log.e("GeminiNano", "Failed to check Gemini Nano status", e)
                isGeminiNanoAvailable = false
            } finally {
                isCheckingStatus = false
            }
        }
    }

    override suspend fun generateResponse(prompt: String): String = withContext(ioDispatcher) {
        // Wait briefly if status is still being checked
        var retries = 0
        while (isCheckingStatus && retries < 10) {
            kotlinx.coroutines.delay(100)
            retries++
        }

        if (isGeminiNanoAvailable) {
            try {
                val request = generateContentRequest(TextPart(prompt)) { }
                val response = generativeModel.generateContent(request)

                // Get the text from the response object
                val responseText = response.candidates.firstOrNull()?.text
                responseText ?: "No response generated by Gemini Nano"
            } catch (e: Exception) {
                Log.e("GeminiNano", "Error generating response from Gemini Nano, using fallback", e)
                fallbackLlm.generateResponse(prompt)
            }
        } else {
            Log.d("GeminiNano", "Gemini Nano not available, using fallback LLM")
            fallbackLlm.generateResponse(prompt)
        }
    }

    override suspend fun generateVector(prompt: String): List<Float> {
        // ML Kit GenAI Prompt API does not currently expose embeddings.
        // Fallback to MediaPipe mock or previous implementation
        return fallbackLlm.generateVector(prompt)
    }
}
